-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- vim.g.mapleader = " "
--
--
-- vim.g.maplocalleader = "\\"
--
-- vim.g.camelcasemotion_key = "<leader>"
-- vim.keymap.set("n", "<leader>/", ":noh<CR>")
--
-- -- Search settings
-- vim.opt.ignorecase = true
-- vim.opt.smartcase = true
--
-- -- Enable true color support
-- vim.opt.termguicolors = true
-- vim.api.nvim_create_autocmd("TextYankPost", {
--   group = vim.api.nvim_create_augroup("highlight_yank", {}),
--   desc = "Highlight selection on yank",
--   pattern = "*",
--   callback = function()
--     vim.highlight.on_yank({ higroup = "IncSearch", timeout = 250 })
--   end,
-- })
--
-- vim.opt.clipboard = "unnamedplus"
-- -- Dial.nvim (modify numbers, dates, booleans with cyclic patterns)
-- vim.keymap.set("n", "<C-a>", function()
--   require("dial.map").manipulate("increment", "normal")
-- end)
-- vim.keymap.set("n", "<C-x>", function()
--   require("dial.map").manipulate("decrement", "normal")
-- end)
-- vim.keymap.set("n", "g<C-a>", function()
--   require("dial.map").manipulate("increment", "gnormal")
-- end)
-- vim.keymap.set("n", "g<C-x>", function()
--   require("dial.map").manipulate("decrement", "gnormal")
-- end)
-- vim.keymap.set("x", "<C-a>", function()
--   require("dial.map").manipulate("increment", "visual")
-- end)
-- vim.keymap.set("x", "<C-x>", function()
--   require("dial.map").manipulate("decrement", "visual")
-- end)
-- vim.keymap.set("x", "g<C-a>", function()
--   require("dial.map").manipulate("increment", "gvisual")
-- end)
-- vim.keymap.set("x", "g<C-x>", function()
--   require("dial.map").manipulate("decrement", "gvisual")
-- end)
--
-- -- telescope
-- -- vim.keymap.set("n", "<leader>ft", ":Telescope<CR>")
-- -- vim.keymap.set("n", "<leader>ff", ":Telescope find_files<CR>")
-- -- vim.keymap.set("n", "<leader>fg", ":Telescope live_grep<CR>")
-- -- vim.keymap.set("n", "<leader>fb", ":Telescope buffers<CR>")
-- -- vim.keymap.set("n", "<leader>fh", ":Telescope help_tags<CR>")
-- -- vim.keymap.set("n", "<leader>fr", ":Telescope resume<CR>")
-- -- vim.keymap.set("n", "<leader>fb", ":Telescope buffers<CR>")
-- -- vim.keymap.set("n", "<leader>fo", ":Telescope oldfiles<CR>")
-- -- vim.keymap.set("n", "<leader>fc", ":Telescope current_buffer_fuzzy_find<CR>")
-- -- vim.keymap.set("n", "<leader>o", "<cmd>Telescope lsp_document_symbols<cr>", { desc = "Document symbols" })
--
-- -- diagnostic
-- vim.keymap.set("n", "gl", function()
--   vim.diagnostic.open_float({ wrap = false })
-- end, { desc = "Show diagnostic" })
-- vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Previos diagnostic" })
-- vim.keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Next Diagnostic" })
-- local gotoDiagnosticErrors = function()
--   require("telescope.builtin").diagnostics({ severity = vim.diagnostic.severity.ERROR })
-- end
-- vim.keymap.set("n", "]E", gotoDiagnosticErrors, { desc = "View errors in diagnostic" })
-- vim.keymap.set("n", "[E", gotoDiagnosticErrors, { desc = "View errors in diagnostic" })
-- vim.keymap.set("n", "<leader>du", function()
--   require("dapui").toggle()
-- end, { desc = "Toggle dapUI" })
--
-- -- Leap.nvim (jump to any character)
-- vim.keymap.set({ "n", "x", "o" }, "s", "<Plug>(leap-anywhere)")
-- vim.keymap.set("n", "S", "<Plug>(leap-from-window)")
-- vim.opt.gdefault = true
--
-- -- rename symbol
-- vim.keymap.set("n", "<F2>", vim.lsp.buf.rename, { desc = "Rename symbol" })
--
-- -- go to next quickfix item
-- vim.keymap.set("n", "<M-j>", ":cnext<CR>")
-- vim.keymap.set("n", "<M-k>", ":cprev<CR>")
--
-- vim.opt.number = true
-- vim.opt.relativenumber = true
--
-- -- Disable automatic comment continuation
-- vim.api.nvim_create_autocmd("BufEnter", {
--   callback = function()
--     vim.opt.formatoptions:remove({ "c", "r", "o" })
--   end,
-- })
--
-- -- copy filename
-- vim.keymap.set("n", "<leader>cf", function()
--   vim.fn.setreg("+", vim.fn.expand("%:t"))
--   print("Copied: " .. vim.fn.expand("%:t"))
-- end, { desc = "Copy filename" })
-- vim.keymap.set("n", "<leader>cp", function()
--   vim.fn.setreg("+", vim.fn.expand("%"))
--   print("Copied relative path: " .. vim.fn.expand("%"))
-- end, { desc = "Copy relative path" })
--
-- vim.opt.autoread = true
-- vim.cmd.colorscheme("gruvbox")
--
-- vim.keymap.set("n", "<leader>en", ":e $MYVIMRC<CR>", { desc = "Edit Neovim config" })
-- vim.keymap.set("n", "<leader>et", ":e ~/.tmux.conf<CR>", { desc = "Edit tmux config" })
-- vim.opt.ruler = true
-- -- vim.opt.cursorline = true
-- -- vim.opt.cursorlineopt = "both"
